language: node_js
node_js:
- '6'
- '8'
- '10'
cache:
  directories:
  - node_modules
sudo: false
services:
- rabbitmq
- redis
env:
  global:
  - LOG_LEVEL=error
  - RABBITMQ_USERNAME=guest
  - RABBITMQ_PASSWORD=guest
  - REDIS_HOST=localhost
  - REDIS_PORT=6379
script:
- npm run lint
- npm run coverage
- npm run functional
- npm run integration
- npm run build && npm run build:clean
# after_success:
# - npm run coveralls
# - npm run codeclimate
notifications:
  email: false
